;
;	 ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
;	██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
;	██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
;	██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
;	 ██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
; 	 ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

alpha = #0000ffff
bg = #282c34
fg = #abb2bf


;; for 50% transparent
trans1 = #80000000 
;; 100% transparent
trans2 = #00


;; colors
black = #282c34 
white = #abb2bf 
red = #e06c75
green = #98c379
yellow = #e5c07b
blue = #61afef
purple = #c678dd
cyan = #56b6c2
teal = 
orange = 
pink = 


;; xrdb colors
;; Uncomment this if you want to use color from .Xdefaults or Xresources
;black = ${xrdb:color0}
;white = ${xrdb:color7}
;red = ${xrdb:color1}
;green = ${xrdb:color2}
;yellow = ${xrdb:color3}
;blue = ${xrdb:color4}
;purple = ${xrdb:color5}
;cyan = ${xrdb:color6}


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
