;
;	 ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
;	██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
;	██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
;	██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
;	 ██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
; 	 ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

alpha = #0000ffff
bg = #1a1b26
bg1 = #2c2e42 
bg2 = #3f425e
fg = #cccccc


;; for 50% transparent
trans1 = #80000000 
;; 100% transparent
trans2 = #00


;; colors
; night
black =  #1a1b26 
; storm
black1 = #24283b
white = #cccccc
red = #f7768e 
green = #9ece6a
yellow = #e0af68
blue = #7dcfff
purple = #bb9af7
cyan = #b4f9f8
teal = #73daca
orange = #ff9e64
gray = #9aa5ce
indigo = #414868
cream = #cfc9c2
pink = 


;; xrdb colors
;; Uncomment this if you want to use color from .Xdefaults or Xresources
;black = ${xrdb:color0}
;white = ${xrdb:color7}
;red = ${xrdb:color1}
;green = ${xrdb:color2}
;yellow = ${xrdb:color3}
;blue = ${xrdb:color4}
;purple = ${xrdb:color5}
;cyan = ${xrdb:color6}


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
